package com.bms.sumithforward;

import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * One-time (or scheduled) export: pulls every bus/camera your CCU already
 * knows about from your own database and writes cameras.csv for
 * RtmpForwarder — so nobody hand-types 7000 rows.
 *
 * Fill in the three things marked FILL IN below to match your actual
 * database: the JDBC connection details, the SQL query, and the column
 * mapping. Everything else (CSV writing, escaping) is done.
 *
 * If your fleet inventory lives behind an HTTP API instead of a direct DB
 * connection, replace the body of fetchRows() with an HTTP call + JSON
 * parse instead of JDBC — the rest of this file (CSV writing) doesn't
 * change.
 *
 * Usage:
 *   java com.bms.sumithforward.GenerateCameraCsv cameras.csv
 */
public final class GenerateCameraCsv {

    // ---- FILL IN: your database connection ----
    private static final String JDBC_URL = "jdbc:mysql://localhost:3306/your_ccu_db";
    private static final String DB_USER = "your_user";
    private static final String DB_PASSWORD = "your_password";

    // ---- FILL IN: the query that lists every camera across your fleet ----
    // Must return (at minimum) a bus identifier, a camera identifier, and
    // that camera's local access URL — adjust column names to match your
    // schema.
    private static final String QUERY =
            "SELECT bus_id, camera_id, local_stream_url FROM cameras WHERE active = 1";

    public static void main(String[] args) throws Exception {
        if (args.length < 1) {
            System.err.println("Usage: java com.bms.sumithforward.GenerateCameraCsv <output-cameras.csv>");
            System.exit(1);
        }

        int written = 0;
        try (Connection conn = DriverManager.getConnection(JDBC_URL, DB_USER, DB_PASSWORD);
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(QUERY);
             PrintWriter out = new PrintWriter(new FileWriter(args[0]))) {

            out.println("# streamKey,inputUrl — generated by GenerateCameraCsv, do not hand-edit");
            while (rs.next()) {
                // ---- FILL IN: map your columns to streamKey/inputUrl ----
                String busId = rs.getString("bus_id");
                String cameraId = rs.getString("camera_id");
                String inputUrl = rs.getString("local_stream_url");

                String streamKey = busId + "_" + cameraId; // must stay unique across the whole fleet
                out.println(csvEscape(streamKey) + "," + csvEscape(inputUrl));
                written++;
            }
        } catch (SQLException e) {
            System.err.println("Database query failed: " + e.getMessage());
            System.exit(1);
        }

        System.out.println("Wrote " + written + " camera(s) to " + args[0]);
    }

    private static String csvEscape(String value) {
        if (value == null) {
            return "";
        }
        if (value.contains(",") || value.contains("\"")) {
            return "\"" + value.replace("\"", "\"\"") + "\"";
        }
        return value;
    }

    private GenerateCameraCsv() {
    }
}
